import {
	AppstoreOutlined,
	BorderOutlined,
	CarFilled,
	CarOutlined,
	ClockCircleFilled,
	ClockCircleOutlined,
	CoffeeOutlined,
	CrownOutlined,
	EyeOutlined,
	GiftOutlined,
	HeartOutlined,
	HomeOutlined,
	InboxOutlined,
	LaptopOutlined,
	ManOutlined,
	MobileOutlined,
	SafetyCertificateOutlined,
	ShoppingCartOutlined,
	ShoppingOutlined,
	SkinOutlined,
	TabletOutlined,
	TagsOutlined,
	TrophyOutlined,
	WomanOutlined,
} from "@ant-design/icons";
import type { AntdIconProps } from "@ant-design/icons/es/components/AntdIcon";
import type { ComponentType } from "react";

const categoryIconMap: Record<string, ComponentType<AntdIconProps>> = {
	"beauty": SkinOutlined,
	"fragrances": GiftOutlined,
	"furniture": HomeOutlined,
	"groceries": ShoppingCartOutlined,
	"home-decoration": AppstoreOutlined,
	"kitchen-accessories": CoffeeOutlined,
	"laptops": LaptopOutlined,
	"mens-shirts": ManOutlined,
	"mens-shoes": SafetyCertificateOutlined,
	"mens-watches": ClockCircleOutlined,
	"mobile-accessories": MobileOutlined,
	"motorcycle": CarOutlined,
	"skin-care": HeartOutlined,
	"smartphones": MobileOutlined,
	"sports-accessories": TrophyOutlined,
	"sunglasses": EyeOutlined,
	"tablets": TabletOutlined,
	"tops": TagsOutlined,
	"vehicle": CarFilled,
	"womens-bags": CrownOutlined,
	"womens-dresses": WomanOutlined,
	"womens-jewellery": InboxOutlined,
	"womens-shoes": ShoppingOutlined,
	"womens-watches": ClockCircleFilled,

	"fallback": BorderOutlined,
};

export { categoryIconMap };
