import {
	AppstoreOutlined,
	CarFilled,
	CarOutlined,
	ClockCircleFilled,
	ClockCircleOutlined,
	CoffeeOutlined,
	CrownOutlined,
	EyeOutlined,
	GiftOutlined,
	HeartOutlined,
	HomeOutlined,
	InboxOutlined,
	LaptopOutlined,
	ManOutlined,
	MobileOutlined,
	SafetyCertificateOutlined,
	ShoppingCartOutlined,
	ShoppingOutlined,
	SkinOutlined,
	TabletOutlined,
	TagsOutlined,
	TrophyOutlined,
	WomanOutlined,
} from "@ant-design/icons";
import type { AntdIconProps } from "@ant-design/icons/es/components/AntdIcon";
import type { ComponentType } from "react";

const categoryIcons: ComponentType<AntdIconProps>[] = [
	SkinOutlined,
	GiftOutlined,
	HomeOutlined,
	ShoppingCartOutlined,
	AppstoreOutlined,
	CoffeeOutlined,
	LaptopOutlined,
	ManOutlined,
	SafetyCertificateOutlined,
	ClockCircleOutlined,
	MobileOutlined,
	CarOutlined,
	HeartOutlined,
	MobileOutlined,
	TrophyOutlined,
	EyeOutlined,
	TabletOutlined,
	TagsOutlined,
	CarFilled,
	CrownOutlined,
	WomanOutlined,
	InboxOutlined,
	ShoppingOutlined,
	ClockCircleFilled,
];

export { categoryIcons };
